Repository recurly/recurly-client-python, pull requests merged in 2019-06, with the labels that each got.

#293 Docs, add network error, kwargs for pagination
  .readthedocs.yml
  .travis.yml
  README.md
  docs/Makefile
  docs/README.md
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/recurly.rst
  recurly/__init__.py
  recurly/base_client.py
  recurly/client.py
  recurly/pager.py
  recurly/resources.py
  requirements-test.txt
  scripts/build
  tests/test_base_client.py
  tests/test_client.py
Labels: v3

#294 2 small bug fixes
  recurly/base_client.py
  recurly/pager.py
  tests/mock_client.py
  tests/test_base_client.py
  tests/test_pager.py
Labels: bug, v3

#295 Fix list_sites bug
  recurly/client.py
Labels: v3

#297 Documentation and casting improvements
  recurly/__init__.py
  recurly/resource.py
  recurly/resources.py
  scripts/test
  tests/mock_resources.py
  tests/test_base_client.py
  tests/test_pager.py
  tests/test_resource.py
  tests/test_resources.py
Labels: v3

#299 Add recurly-style User-Agent
  docs/README.md
  recurly/__init__.py
  recurly/base_client.py
  setup.py
Labels: v3

#296 Add 3DS tokens to transaction error and billing info
  recurly/__init__.py
  recurly/errors.py
Labels: new feature

#301 Latest v2018-08-09 Changes
  recurly/client.py
  recurly/resources.py
Labels: v3

#302 3.0b4
  docs/README.md
  recurly/__init__.py
Labels: v3
