Repository recurly/recurly-client-python, pull requests merged in 2019-12, with the labels that each got.

#341 Release 3.3.0
  .bumpversion.cfg
  recurly/__init__.py
  tests/test_resource.py
Labels: v3

#342 Convert Array params to CSV strings
  .bumpversion.cfg
  recurly/__init__.py
  recurly/pager.py
Labels: bug, v3

#343 Release 2.9.13
  CHANGELOG.md
  recurly/__init__.py
Labels: V2
