Repository recurly/recurly-client-python, pull requests merged in 2020-11, with the labels that each got.

#459 Support item-specific coupons
  recurly/__init__.py
  tests/fixtures/coupon/item-coupon-created.xml
  tests/fixtures/coupon/item-coupon-deleted.xml
  tests/test_resources.py
Labels: V2

#461 Latest Changes for 2019-10-10 (Wallet, Item Coupons)
  openapi/api.yaml
  recurly/client.py
  recurly/errors.py
  recurly/resources.py
Labels: enhancement

#462 Release 2.9.22
  CHANGELOG.md
  recurly/__init__.py
Labels: V2

#464 Expose response fields and add field to test fixture
  recurly/__init__.py
  tests/fixtures/billing-info/account-iban-created.xml
Labels: V2

#465 Latest Changes for 2019-10-10
  openapi/api.yaml
  recurly/client.py
  recurly/resources.py
Labels: enhancement

#466 Update readme with memo about headers
  README.rst
Labels: V2, documentation

#468 Release 2.9.23
  CHANGELOG.md
  recurly/__init__.py
Labels: V2
