Repository recurly/recurly-client-python, pull requests merged in 2020-08, with the labels that each got.

#417 Add tiers attribute to sub add-on
  recurly/__init__.py
  tests/fixtures/subscribe-add-on/subscribed.xml
  tests/fixtures/subscribe-add-on/tiered-add-on-created.xml
  tests/test_resources.py
Labels: V2

#421 Add tax identifier fields to billing info
  recurly/__init__.py
Labels: V2

#424 Release 2.9.19
  CHANGELOG.md
  recurly/__init__.py
Labels: V2

#428 Mon Aug 31 19:49:18 UTC 2020 Upgrade API version v2019-10-10
  openapi/api.yaml
  recurly/resources.py
Labels: enhancement

#427 Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation
