Repository recurly/recurly-client-python, pull requests merged in 2020-09, with the labels that each got.

#431 New endpoint to verify an account's billing information
  recurly/__init__.py
  tests/fixtures/billing-info/account-embed-created.xml
  tests/fixtures/billing-info/verified-with-gateway-code-200.xml
  tests/test_resources.py
Labels: V2

#435 Set url value to access either href and url
  recurly/__init__.py
Labels: V2

#436 Latest Changes for 2019-10-10 (Automated Exports, additional resource data attributes)
  openapi/api.yaml
  recurly/client.py
  recurly/resources.py
Labels: enhancement

#438 Add ability to verify billing_info without fetching account first
  recurly/__init__.py
  tests/test_resources.py
Labels: V2

#434 Release 2.9.20
  CHANGELOG.md
  recurly/__init__.py
  tests/fixtures/billing-info/account-embed-created.xml
  tests/fixtures/billing-info/verified-with-gateway-code-200.xml
  tests/test_resources.py
Labels: V2

#439 Use ErrorMayHaveTransaction instead of Error
  recurly/resource.py
  tests/mock_resources.py
Labels: bug
