Repository recurly/recurly-client-python, pull requests merged in 2021-11, with the labels that each got.

#524 Splitting docs out of build script
  .travis.yml
  scripts/build
  scripts/docs
Labels: v4, internal

#525 Splitting docs out of build script
  .travis.yml
  scripts/build
  scripts/docs
Labels: v3, internal

#522 Generated Latest Changes for v2019-10-10 (Account Hierarchy Invoice Rollup)
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#523 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  recurly/resources.py
Labels: v4
