Repository recurly/recurly-client-python, pull requests merged in 2021-06, with the labels that each got.

#497 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  recurly/client.py
  recurly/resources.py
Labels: v4

#500 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#499 Add tax_type and tax_region to TaxDetail
  recurly/__init__.py
  tests/fixtures/invoice/show-invoice.xml
  tests/test_resources.py
Labels: V2

#494 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#501 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
  recurly/client.py
  recurly/resources.py
Labels: v3
