Repository recurly/recurly-client-python, pull requests merged in 2022-04, with the labels that each got.

#551 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
  recurly/pager.py
  requirements-optional.txt
  requirements-test.txt
Labels: v4, internal

#557 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
  recurly/pager.py
  requirements-optional.txt
  requirements-test.txt
Labels: v3, internal

#558 Adding github actions
  .github/workflows/ci.yml
  requirements-test.txt
  scripts/build
  scripts/test
Labels: V2, internal

#552 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#548 Generated Latest Changes for v2021-02-25 (Percentage tiers feature)
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#553 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#554 Add support for percentage tiered add-ons
  .travis.yml
  recurly/__init__.py
  tests/fixtures/add-on/created-percentage-tiered.xml
  tests/fixtures/add-on/exists-percentage-tiered.xml
  tests/fixtures/subscribe-add-on/percentage-tiered-add-on-created.xml
  tests/fixtures/subscribe-add-on/subscribed.xml
  tests/test_resources.py
Labels: V2

#561 Generated Latest Changes for v2022-01-01(Ramp Pricing)
  openapi/api.yaml
  recurly/client.py
  recurly/resources.py
Labels: V5
