Repository recurly/recurly-client-python, pull requests merged in 2022-08, with the labels that each got.

#572 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#573 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#584 Added support for ramp-pricing purchases
  recurly/__init__.py
  recurly/resource.py
  tests/fixtures/purchase-with-ramp-intervals/authorized.xml
  tests/fixtures/purchase-with-ramp-intervals/invoiced.xml
  tests/fixtures/purchase-with-ramp-intervals/pending.xml
  tests/fixtures/purchase-with-ramp-intervals/previewed.xml
  tests/fixtures/purchase-with-ramp/authorized.xml
  tests/fixtures/purchase-with-ramp/invoiced.xml
  tests/fixtures/purchase-with-ramp/pending.xml
  tests/fixtures/purchase-with-ramp/previewed.xml
  tests/test_resources.py
Labels: V2

#586 Fixes bug with put_dunning_campaign_bulk_update
  openapi/api.yaml
  recurly/client.py
Labels: bug, v4
