Repository recurly/recurly-client-python, pull requests merged in 2023-01, with the labels that each got.

#617 Update CI
  .github/workflows/ci.yml
Labels: v4, internal

#616 Update CI
  .github/workflows/ci.yml
Labels: v3, internal

#614 Generated Latest Changes for v2019-10-10 (Account Preferred Time Zone)
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#615 Generated Latest Changes for v2021-02-25 (Account Preferred Time Zone)
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#619 Add Support for Custom Fields on Purchase Adjustments
  recurly/__init__.py
  tests/README.md
  tests/fixtures/purchase-with-custom-fields-on-adjustments/authorized.xml
  tests/fixtures/purchase-with-custom-fields-on-adjustments/cancelled.xml
  tests/fixtures/purchase-with-custom-fields-on-adjustments/captured.xml
  tests/fixtures/purchase-with-custom-fields-on-adjustments/invoiced.xml
  tests/fixtures/purchase-with-custom-fields-on-adjustments/pending.xml
  tests/fixtures/purchase-with-custom-fields-on-adjustments/previewed.xml
  tests/test_resources.py
Labels: V2

#621 Generated Latest Changes for v2021-02-25 (Custom Fields on Line Items)
  openapi/api.yaml
  recurly/resources.py
Labels: v4

#622 Generated Latest Changes for v2019-10-10 (Custom Fields on Line Items)
  openapi/api.yaml
  recurly/resources.py
Labels: v3

#618 Added decline_code to TransactionError
  recurly/__init__.py
  recurly/errors.py
  tests/fixtures/transaction/declined-transaction.xml
  tests/test_resources.py
  tests/tests_errors.py
Labels: V2

#624 Add support for custom field definitions
  recurly/__init__.py
  tests/fixtures/custom_field_definitions/list.xml
  tests/fixtures/custom_field_definitions/list_charge.xml
  tests/fixtures/custom_field_definitions/show.xml
  tests/test_resources.py
Labels: V2
